/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBioimpedanciaRouteImport } from './routes/_app.bioimpedancia'
import { Route as AppAlunoIndexRouteImport } from './routes/_app.aluno.index'
import { Route as AppAlunoEvolucaoRouteImport } from './routes/_app.aluno.evolucao'
import { Route as AppAlunoComparativoRouteImport } from './routes/_app.aluno.comparativo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBioimpedanciaRoute = AppBioimpedanciaRouteImport.update({
  id: '/bioimpedancia',
  path: '/bioimpedancia',
  getParentRoute: () => AppRoute,
} as any)
const AppAlunoIndexRoute = AppAlunoIndexRouteImport.update({
  id: '/aluno/',
  path: '/aluno/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlunoEvolucaoRoute = AppAlunoEvolucaoRouteImport.update({
  id: '/aluno/evolucao',
  path: '/aluno/evolucao',
  getParentRoute: () => AppRoute,
} as any)
const AppAlunoComparativoRoute = AppAlunoComparativoRouteImport.update({
  id: '/aluno/comparativo',
  path: '/aluno/comparativo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bioimpedancia': typeof AppBioimpedanciaRoute
  '/dashboard': typeof AppDashboardRoute
  '/usuarios': typeof AppUsuariosRoute
  '/aluno/comparativo': typeof AppAlunoComparativoRoute
  '/aluno/evolucao': typeof AppAlunoEvolucaoRoute
  '/aluno/': typeof AppAlunoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bioimpedancia': typeof AppBioimpedanciaRoute
  '/dashboard': typeof AppDashboardRoute
  '/usuarios': typeof AppUsuariosRoute
  '/aluno/comparativo': typeof AppAlunoComparativoRoute
  '/aluno/evolucao': typeof AppAlunoEvolucaoRoute
  '/aluno': typeof AppAlunoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bioimpedancia': typeof AppBioimpedanciaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/aluno/comparativo': typeof AppAlunoComparativoRoute
  '/_app/aluno/evolucao': typeof AppAlunoEvolucaoRoute
  '/_app/aluno/': typeof AppAlunoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bioimpedancia'
    | '/dashboard'
    | '/usuarios'
    | '/aluno/comparativo'
    | '/aluno/evolucao'
    | '/aluno/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bioimpedancia'
    | '/dashboard'
    | '/usuarios'
    | '/aluno/comparativo'
    | '/aluno/evolucao'
    | '/aluno'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/bioimpedancia'
    | '/_app/dashboard'
    | '/_app/usuarios'
    | '/_app/aluno/comparativo'
    | '/_app/aluno/evolucao'
    | '/_app/aluno/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bioimpedancia': {
      id: '/_app/bioimpedancia'
      path: '/bioimpedancia'
      fullPath: '/bioimpedancia'
      preLoaderRoute: typeof AppBioimpedanciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aluno/': {
      id: '/_app/aluno/'
      path: '/aluno'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AppAlunoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aluno/evolucao': {
      id: '/_app/aluno/evolucao'
      path: '/aluno/evolucao'
      fullPath: '/aluno/evolucao'
      preLoaderRoute: typeof AppAlunoEvolucaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aluno/comparativo': {
      id: '/_app/aluno/comparativo'
      path: '/aluno/comparativo'
      fullPath: '/aluno/comparativo'
      preLoaderRoute: typeof AppAlunoComparativoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBioimpedanciaRoute: typeof AppBioimpedanciaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppAlunoComparativoRoute: typeof AppAlunoComparativoRoute
  AppAlunoEvolucaoRoute: typeof AppAlunoEvolucaoRoute
  AppAlunoIndexRoute: typeof AppAlunoIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBioimpedanciaRoute: AppBioimpedanciaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppAlunoComparativoRoute: AppAlunoComparativoRoute,
  AppAlunoEvolucaoRoute: AppAlunoEvolucaoRoute,
  AppAlunoIndexRoute: AppAlunoIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
